development:
  database: thenewspanel
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

test:
  database: thenewspanel

production:
  host: localhost
  adapter: postgresql
  encoding: utf8
  database: thenewspanel_production
  pool: 5
  username: <%= ENV['deploy'] %>
  password: <%= ENV['boomboom0'] %>
